inventory_group_all_user_profile:
  vscode:
    extenssions:
      - alefragnani.project-manager
      - CoenraadS.bracket-pair-colorizer-2
      - haaaad.ansible
      - timonwong.ansible-autocomplete
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - wholroyd.jinja